### ISSUE TITLE
Default time to settle down is not overridden in pc_stop_collect.sh

### ISSUE THREAD

**Issue by ghjansen** [RestComm/PerfCorder#66]
When the parameter `-s` is informed followed by a specific value like `-s 360`, the default value `180` is not overridden by `360`. This may be caused by a missing option `s:` inside the `getopts` configuration: https://github.com/RestComm/PerfCorder/blob/master/src/main/resources/pc_stop_collect.sh#L91

**Comment by jaimecasero** [comment]
https://github.com/RestComm/PerfCorder/blob/8c51d18996ea5340de5628f42145ddb9b1815e42/src/main/resources/pc_stop_collect.sh#L91 we need to update the optsarg pattern, good catch!!
